# Site Info
title: '아름이의 개발로그'
tagline: '아름이의 개발로그'
description: '프로그래밍 공부하며 기록하기'
baseurl: ""
url: https://aiody.github.io
logo: '/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: AREUM KIM
  description: A passionate <strong>developer and researcher</strong>, learning to be a giant.
  # gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    #linkedin:  https://www.linkedin.com/in/lizhihao
    github:    https://github.com/aiody
    # facebook:  <hide>
    # twitter:   https://twitter.com/Li_Zhihao
    email:     mailto:aiody329@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Categories:           
    - '/blog/categories/'
    # - { Categories: '/blog/categories/' }
    # - { Tags: '/blog/tags/' }
    - { TIL (Today I Learned): '#til' }
    - { JavaScript: '#javascript' }
  About:          
    - '/about/'
  # Github Project: 
    # - 'http://codinfox.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: '' # leave blank if you don't want google analytics
disqus_short_name: 'your_short_name' # leave blank if you don't want disqus

# Use the following plug-ins
# gems:
  # - jekyll-paginate

